☁️ Automation

diff --git a/.config/taskfiles/docker/Taskfile.yml b/.config/taskfiles/docker/Taskfile.yml
--- a/.config/taskfiles/docker/Taskfile.yml
+++ b/.config/taskfiles/docker/Taskfile.yml
@@ -30,24 +30,35 @@ tasks:
       success: Finished running Docker build sequence
     cmds:
       - |
-        if [ -f Docker.test.yml ]; then
-          task docker:build:fat
-          if [ "$(jq -r '.blueprint.dockerSlimCommand' package.json)" != 'null' ]; then
+        if [ -d ./test/structure ]; then
+          TESTS="$(find ./test/structure -mindepth 1 -maxdepth 1 -type -f -name "*.yml")"
+          if echo "$TESTS" | grep '.yml'; then
+            for TEST_FILE in $TESTS; do
+              TARGET="$(echo "$TEST_FILE" | sed 's/.*\/\([^\/]*\).yml$/\1/')"
+              if [ "$(jq --arg slug "$TARGET" '.blueprint.dockerSlimCommand[$slug]' package.json)" != 'null' ]; then
+                task docker:build:slim -- "$TARGET"
+              else
+                .config/log warn 'The `.blueprint.dockerSlimCommand` is missing - skipping slim build and building just a regular image'
+                task docker:build:fat -- "$TARGET"
+              fi
+            done
+          else
+            .config/log error 'The `./test/structure` folder is present but there are no container-structure-tests in it. Add tests \
+            for each build target in the `Dockerfile` that you would like to generate an image for.'
+            exit 1
+          fi
+        else
+          .config/log info 'No `./test/structure` folder is present so assuming there is only one build target'
+          if [ "$(jq -r '.blueprint.dockerSlimCommand' package.json)" != null ]; then
+            .config/log info '`.blueprint.dockerSlimCommand` is present in `package.json` so building both a `latest` and `slim` image'
             task docker:build:slim
+          else
+            task docker:build:fat
           fi
         fi
-      - |
-        for TESTFILE in Docker.*.test.yml; do
-          if [ "$TESTFILE" != 'Docker.*.test.yml' ]; then
-            TEST_IMAGE_SLUG="$(echo $TESTFILE | sed 's/^Docker.//' | sed 's/.test.yml$//')"
-            if [ "$(jq --arg slug "$TEST_IMAGE_SLUG" '.blueprint.dockerSlimCommand[$slug]' package.json)" != 'null' ]; then
-              task docker:build:slim -- "$TEST_IMAGE_SLUG"
-            else
-              .config/log warn 'The `.blueprint.dockerSlimCommand` is missing - skipping slim build and building just a regular image'
-              task docker:build:fat -- "$TEST_IMAGE_SLUG"
-            fi
-          fi
-        done
+    preconditions:
+      - sh: test -f Dockerfile
+        msg: The `Dockerfile` must be present in order to build it
 
   login:
     deps:
@@ -82,21 +93,25 @@ tasks:
       a `Docker.build1.test.yml` and `Docker.build2.test.yml` container-structure-test.
     cmds:
       - |
-        if [ -f Docker.test.yml ]; then
+        if [ -d ./test/structure ]; then
+          TESTS="$(find ./test/structure -mindepth 1 -maxdepth 1 -type -f -name "*.yml")"
+          if echo "$TESTS" | grep '.yml'; then
+            for TEST_FILE in $TESTS; do
+              TARGET="$(echo "$TEST_FILE" | sed 's/.*\/\([^\/]*\).yml$/\1/')"
+              task docker:publish:images -- "$TARGET"
+            done
+          else
+            .config/log error 'The `./test/structure` folder is present but there are no container-structure-tests in it. Add tests \
+            for each build target in the `Dockerfile` that you would like to generate an image for.'
+            exit 1
+          fi
+        else
+          .config/log info 'No `./test/structure` folder is present so assuming there is only one build target'
           task docker:publish:images
         fi
-      - |
-        for TESTFILE in Docker.*.test.yml; do
-          if [ "$TESTFILE" != 'Docker.*.test.yml' ]; then
-            TEST_IMAGE_SLUG="$(echo $TESTFILE | sed 's/^Docker.//' | sed 's/.test.yml$//')"
-            task docker:publish:images -- "$TEST_IMAGE_SLUG"
-          fi
-        done
+      - task: pushrm
 
   publish:image:
-    vars:
-      SLUG:
-        sh: echo "{{if .CLI_ARGS}}{{.CLI_ARGS}}{{else}}$(jq -r '.blueprint.slug' package.json){{end}}"
     log:
       error: Failed to tag / push `{{.DOCKER_IMAGE}}:{{.TARGET_TAG}}`
       start: Tagging and pushing `{{.DOCKER_IMAGE}}:{{.TARGET_TAG}}`
@@ -104,14 +119,6 @@ tasks:
     cmds:
       - docker tag {{.DOCKER_IMAGE}}:{{.SOURCE_TAG}} {{.DOCKER_IMAGE}}:{{.TARGET_TAG}}
       - docker push {{.DOCKER_IMAGE}}:{{.TARGET_TAG}}
-      - |
-        if [ '{{.REPOSITORY_SUBTYPE}}' == 'codeclimate' ] && echo '{{.SLUG}}' | grep 'codeclimate-'; then
-          .config/log info 'Uploading to tag `{{.TARGET_TAG}}-codeclimate` since this is a codeclimate repository'
-          TARGET_IMAGE="$(echo '{{.SLUG}}' | sed 's/^codeclimate-//')"
-          docker tag {{.DOCKER_IMAGE}}:{{.SOURCE_TAG}} "{{.DOCKERHUB_PROFILE}}/${TARGET_IMAGE}:{{.TARGET_TAG}}-codeclimate"
-          docker push "{{.DOCKERHUB_PROFILE}}/${TARGET_IMAGE}:{{.TARGET_TAG}}-codeclimate"
-          .config/log success 'Uploaded tag `{{.TARGET_TAG}}-codeclimate` successfully'
-        fi
     status:
       - if [[ '{{.SOURCE_TAG}}' == 'slim' ]]; then [[ '{{.SLIM_ENABLED}}' == 'false' ]]; fi
 
@@ -119,6 +126,7 @@ tasks:
     vars:
       MAJOR_VERSION:
         sh: jq -r '.version' package.json | sed 's/\..*\..*$//'
+      TAG_POST: '{{if (contains "codeclimate" .CLI_ARGS)}}-codeclimate{{end}}'
       VERSION:
         sh: jq -r ".version" package.json
     log:
@@ -128,29 +136,28 @@ tasks:
     cmds:
       - task: publish:image
         vars:
-          SOURCE_TAG: latest
-          TARGET_TAG: '{{.VERSION}}'
+          SOURCE_TAG: latest{{.TAG_POST}}
+          TARGET_TAG: '{{.VERSION}}{{.TAG_POST}}'
       - task: publish:image
         vars:
-          SOURCE_TAG: latest
-          TARGET_TAG: '{{.MAJOR_VERSION}}-latest'
+          SOURCE_TAG: latest{{.TAG_POST}}
+          TARGET_TAG: '{{.MAJOR_VERSION}}-latest{{.TAG_POST}}'
       - task: publish:image
         vars:
-          SOURCE_TAG: latest
-          TARGET_TAG: latest
+          SOURCE_TAG: latest{{.TAG_POST}}
+          TARGET_TAG: latest{{.TAG_POST}}
       - task: publish:image
         vars:
-          SOURCE_TAG: slim
-          TARGET_TAG: '{{.VERSION}}-slim'
+          SOURCE_TAG: slim{{.TAG_POST}}
+          TARGET_TAG: '{{.VERSION}}-slim{{.TAG_POST}}'
       - task: publish:image
         vars:
-          SOURCE_TAG: slim
-          TARGET_TAG: '{{.MAJOR_VERSION}}-slim'
+          SOURCE_TAG: slim{{.TAG_POST}}
+          TARGET_TAG: '{{.MAJOR_VERSION}}-slim{{.TAG_POST}}'
       - task: publish:image
         vars:
-          SOURCE_TAG: slim
-          TARGET_TAG: slim
-      - task: pushrm
+          SOURCE_TAG: slim{{.TAG_POST}}
+          TARGET_TAG: slim{{.TAG_POST}}
 
   pushrm:
     deps:
@@ -249,34 +256,9 @@ tasks:
       start: Initiating Docker test sequence
       success: Successfully completed Docker test sequence
     cmds:
-      - |
-        if [ -f Docker.test.yml ]; then
-          task docker:test:container-structure-test
-          if [ -d test-output ]; then
-            task docker:test:output
-          fi
-        fi
-      - |
-        for TESTFILE in Docker.*.test.yml; do
-          if [ "$TESTFILE" != 'Docker.*.test.yml' ]; then
-            TEST_IMAGE_SLUG="$(echo $TESTFILE | sed 's/^Docker.//' | sed 's/.test.yml$//')"
-            task docker:test:container-structure-test -- "$TEST_IMAGE_SLUG"
-          fi
-        done
-      - |
-        for FOLDER in test/codeclimate*/; do
-          if [ "$FOLDER" != 'test/codeclimate*/' ]; then
-            task lint:codeclimate -- " $FOLDER"
-          fi
-        done
-      - |
-        if [ -d test-output ]; then
-          for TESTFILE in Docker.*.test.yml; do
-            if [ "$TESTFILE" != 'Docker.*.test.yml' ]; then
-              task docker:test:output -- "$TEST_IMAGE_SLUG"
-            fi
-          done
-        fi
+      - task: :docker:test:container-structure-tests
+      - task: :docker:test:output
+      - task: :docker:test:codeclimate
       - task: :docker:test:gitlab-runner
 
   verify:
